// GENERATED by scripts/gen-firmware-data.mjs — do not edit.
// Source of truth: src/lib/tokens.ts and src/lib/data.ts. Run `npm run gen:firmware`.
#pragma once
#include <stdint.h>

/** Every colour and metric the design uses, in one place. */
namespace theme {

// Panel geometry, in the design's own pixels.
inline constexpr int PANEL_WIDTH = 480;
inline constexpr int PANEL_HEIGHT = 320;
inline constexpr int PANEL_PADDING = 16;

inline constexpr uint32_t SURFACE = 0xFFFFFF;
inline constexpr uint32_t INK = 0x101720;
inline constexpr uint32_t MUTED = 0x5A6470;
inline constexpr uint32_t CHIP_INK = 0x3A434F;
inline constexpr uint32_t WASH = 0xEDF0F4;
inline constexpr uint32_t BLUE = 0x2E6FD0;
inline constexpr uint32_t BLUE_WASH = 0xE3ECFA;
inline constexpr uint32_t GAUGE_TRACK = 0xE7ECF2;
inline constexpr uint32_t MAGENTA = 0xD6006E;
inline constexpr uint32_t NEUTRAL_BAR = 0x9AA3AD;
inline constexpr uint32_t ORANGE = 0xE85A14;
inline constexpr uint32_t AMBER = 0xFFC93C;
inline constexpr uint32_t AMBER_INK = 0x3D2A00;
inline constexpr uint32_t GRID_FAINT = 0xEDF0F4;
inline constexpr uint32_t GRID_LIGHT = 0xDFE4EB;
inline constexpr uint32_t AXIS = 0xC6CEDA;
inline constexpr uint32_t BORDER = 0xDFE4EB;
inline constexpr uint32_t TERM_BG = 0x12161C;
inline constexpr uint32_t TERM_TEXT = 0xC7D1DE;
inline constexpr uint32_t TERM_LABEL = 0x9AA6B6;
inline constexpr uint32_t TERM_DIM = 0x6B7787;
inline constexpr uint32_t TERM_LIVE = 0x12907D;
inline constexpr uint32_t TERM_HIGHLIGHT = 0x4FD6B4;

// The insight header runs this gradient. LVGL 9 can angle a gradient; on 8 it
// has to be horizontal, which is close enough at this size.
inline constexpr uint32_t INSIGHT_GRADIENT_FROM = 0x15897E;
inline constexpr uint32_t INSIGHT_GRADIENT_TO = 0x0E4C86;
inline constexpr int INSIGHT_GRADIENT_DEGREES = 120;

}  // namespace theme
