// GENERATED by scripts/gen-firmware-data.mjs — do not edit.
// Source of truth: src/lib/tokens.ts and src/lib/data.ts. Run `npm run gen:firmware`.
#pragma once
#include "MeterData.h"

/**
 * The reading the design was drawn against.
 *
 * Font subset — every character below appears in this data, so lv_font_conv
 * can be given exactly this range and nothing more:
 * " %()*+,-./0123456789:BCDEHILMOSTVWabcdefghiklmnoprstuvwxyz²"
 */
namespace sample {

inline constexpr float kCurrentDaily[] = {
    9.1f, 7.8f, 10.2f, 7.6f, 8.3f};
inline constexpr float kPreviousDaily[] = {
    10.2f, 7.8f, 8.4f, 9.9f, 7.5f, 8.6f, 10.1f, 8.2f, 7.2f, 9.3f, 11.0f, 8.1f, 8.8f, 9.5f, 6.5f, 8.5f, 9.0f, 10.7f, 8.7f, 7.9f, 13.2f, 9.0f, 8.2f, 8.9f, 7.4f, 9.2f, 10.6f, 8.3f, 8.6f, 8.7f};
inline constexpr float kCurrentYear[] = {
    265.0f, 240.0f, 215.0f, 195.0f, 205.0f, 250.0f, 310.0f, 325.0f, 268.0f};
inline constexpr float kPreviousYear[] = {
    272.0f, 248.0f, 220.0f, 198.0f, 208.0f, 255.0f, 318.0f, 332.0f, 275.0f, 232.0f, 240.0f, 262.0f};

inline constexpr LiveReading kHomeLive = {0.41f, 5.0f, "Drawing right now"};
inline constexpr PeriodAverages kHomePrevAverages = {0.37f, 8.93f};

inline constexpr Appliance kAppliances[] = {
    {"Hot Water", ApplianceIcon::HotWater, 514.0f, 22.6f},
    {"Tumble Dryer", ApplianceIcon::TumbleDryer, 282.0f, 12.4f},
    {"Oven", ApplianceIcon::Oven, 259.0f, 11.4f},
    {"Hob", ApplianceIcon::Hob, 243.0f, 10.7f},
    {"Lighting", ApplianceIcon::Lighting, 207.0f, 9.1f}};

inline constexpr const char* kCompareChips[] = {
    "Over 140 m²",
    "3 or more people",
    "Built before 1980",
    "Climate zone B"};

inline constexpr TelegramLine kTelegramLines[] = {
    {"0-0:1.0.0(261005163155W)", "reading time"},
    {"1-0:1.8.1(009427.183*kWh)", "imported, low tariff"},
    {"1-0:1.8.2(007812.455*kWh)", "imported, normal tariff"},
    {"1-0:2.8.1(000312.044*kWh)", "exported, low tariff"},
    {"1-0:2.8.2(000198.620*kWh)", "exported, normal tariff"},
    {"0-0:96.14.0(0001)", "tariff in use"},
    {"1-0:1.7.0(000000.410*kW)", "drawing now"},
    {"1-0:2.7.0(000000.000*kW)", "delivering now"},
    {"1-0:32.7.0(230.1*V)", "voltage"}};

inline constexpr MeterSnapshot kSnapshot = {
    {"My Energy Coach", nullptr, &kHomeLive, nullptr,
     {"October", 265.0f, 43.0f, "So far in October", false}},
    {"September", "closed", nullptr, &kHomePrevAverages,
     {"September", 255.0f, 268.0f, "105% of estimate", true}},
    {"Electric energy consumption", "This is your estimated power consumption by appliance so far in the year.",
     kAppliances, 5},
    {"October Insight", kCurrentDaily, 5, 31},
    {"September Insight", kPreviousDaily, 30, 30},
    {"2026 Insight", kCurrentYear, 9},
    {"2025 Insight", kPreviousYear, 12},
    {nullptr, "than similar homes, month for month", "kWh a month",
     253.0f, 199.0f, kCompareChips, 4, 1982},
    {"September", "than similar homes last month", "kWh in September",
     268.0f, 212.0f, kCompareChips, 4, 1982},
    {kTelegramLines, 9, "1-0:1.7.0"}};

}  // namespace sample
