// GENERATED by scripts/gen-firmware-data.mjs — do not edit.
// Source of truth: src/lib/tokens.ts and src/lib/data.ts. Run `npm run gen:firmware`.
#pragma once
#include "MeterData.h"

/**
 * The reading the design was drawn against.
 *
 * Font subset — every character below appears in this data, so lv_font_conv
 * can be given exactly this range and nothing more:
 * " %()*+,-./0123456789:BCDEHILMOSTVWabcdefghiklmnoprstuvwxyz²"
 */
namespace sample {

inline constexpr float kCurrentDaily[] = {
    22.4f, 19.8f, 24.1f, 18.6f, 21.1f};
inline constexpr float kPreviousDaily[] = {
    21.4f, 18.2f, 19.6f, 22.8f, 17.5f, 20.1f, 23.4f, 19.0f, 16.8f, 21.7f, 23.3f, 18.9f, 20.5f, 22.1f, 15.2f, 19.8f, 21.0f, 22.6f, 20.3f, 18.4f, 28.5f, 20.9f, 19.1f, 20.7f, 17.3f, 21.5f, 21.8f, 19.4f, 20.0f, 20.2f};
inline constexpr float kCurrentYear[] = {
    640.0f, 600.0f, 544.0f, 520.0f, 540.0f, 560.0f, 640.0f, 650.0f, 612.0f};
inline constexpr float kPreviousYear[] = {
    690.0f, 655.0f, 600.0f, 548.0f, 565.0f, 585.0f, 668.0f, 672.0f, 585.0f, 580.0f, 600.0f, 662.0f};

inline constexpr LiveReading kHomeLive = {0.84f, 5.0f, "Drawing right now"};
inline constexpr PeriodAverages kHomePrevAverages = {0.85f, 20.4f};

inline constexpr Appliance kAppliances[] = {
    {"Hot Water", ApplianceIcon::HotWater, 1812.0f, 22.6f},
    {"Tumble Dryer", ApplianceIcon::TumbleDryer, 991.0f, 12.4f},
    {"Oven", ApplianceIcon::Oven, 910.0f, 11.4f},
    {"Hob", ApplianceIcon::Hob, 853.0f, 10.7f},
    {"Lighting", ApplianceIcon::Lighting, 729.0f, 9.1f}};

inline constexpr const char* kCompareChips[] = {
    "Over 140 m²",
    "3 or more people",
    "Built before 1980",
    "Climate zone B"};

inline constexpr TelegramLine kTelegramLines[] = {
    {"0-0:1.0.0(261005163155W)", "reading time"},
    {"1-0:1.8.1(003376.586*kWh)", "imported, low tariff"},
    {"1-0:1.8.2(002774.705*kWh)", "imported, normal tariff"},
    {"1-0:2.8.1(000249.155*kWh)", "exported, low tariff"},
    {"1-0:2.8.2(000234.567*kWh)", "exported, normal tariff"},
    {"0-0:96.14.0(0001)", "tariff in use"},
    {"1-0:1.7.0(000000.840*kW)", "drawing now"},
    {"1-0:2.7.0(000000.000*kW)", "delivering now"},
    {"1-0:32.7.0(230.1*V)", "voltage"}};

inline constexpr MeterSnapshot kSnapshot = {
    {"My Energy Coach", nullptr, &kHomeLive, nullptr,
     {"October", 650.0f, 106.0f, "So far in October", false}},
    {"September", "closed", nullptr, &kHomePrevAverages,
     {"September", 590.0f, 612.0f, "104% of estimate", true}},
    {"Electric energy consumption", "This is your estimated power consumption by appliance so far in the year.",
     kAppliances, 5},
    {"October Insight", kCurrentDaily, 5, 31},
    {"September Insight", kPreviousDaily, 30, 30},
    {"2026 Insight", kCurrentYear, 9},
    {"2025 Insight", kPreviousYear, 12},
    {nullptr, "than similar homes, month for month", "kWh a month",
     590.0f, 465.0f, kCompareChips, 4, 1982},
    {"September", "than similar homes last month", "kWh in September",
     612.0f, 486.0f, kCompareChips, 4, 1982},
    {kTelegramLines, 9, "1-0:1.7.0"}};

}  // namespace sample
